ioos/erddapy

erddapy/erddapy.py

This a workaround to access authenticated ERDDAP servers.
Since the pull requests for pandas to support authentication on `read_csv` requests (https://github.com/pandas-dev/pandas/pull/17087) has not yet been merged, we can read the URL using requests and then pass to pandas using StringIO.

use requests before read_csv to get auth

---

erddapy/utilities.py

Use timestamp() to simplify parse_dates function

Simplify parse_dates

---

requirements-dev.txt
requirements.txt

Only `pandas` and `requests` are mandatory dependencies.

fix dependency specifications

---

CHANGES.txt
erddapy/erddapy.py
notebooks/quick_intro.ipynb

Everything but the `server` and `protocol` should be passed as properties after the object creation.
Closes #36 
Ping @rsignell-usgs

Simplify the erddapy object constructor

---

.travis.yml
README.md
setup.py

I'm sing f-strings, so this makes `erddapy` Python >=3.6 only. I don't think this is a big deal b/c `erddapy` was already Python 3 only and upgrading to 3.6 is not a hassle.
I'm working on integrating the README into the docs, so we only need to modify it in a single place. I'll do that in another PR.

finish PR #40

---

erddapy/erddapy.py
notebooks/quick_intro.ipynb

If I read the docs correctly ERDDAP has 3 Comma Separated Value formats:
- `csv`: with column names in the first row and units on the second
- `csvp`: with both column names and units in the first row
- `csv0` no names/units just data
It looks like the `to_pandas` method should use `csvp` to avoid forcing the user to workaround the second row parsing.

use csvp to merge units in the column name

---

.travis.yml
tests/test_utilities.py

Server testing is mark as expected fail due to transient network issues.

Use pytest xfail

---

CHANGES.txt
erddapy/utilities.py
setup.cfg

Caching the `_check_url_response` results with `functools.lru_cache` to avoid hitting the server multiple times when the URL is the same.

Cache `_check_url_response`

---

.travis.yml

`iris` has a different name at `PyPI`, I'm leaving the original name here with a note for `pip` users.

some improvements to travis-ci config

---

erddapy/erddapy.py

While it is nice to fail early some servers re-direct and this check may lead to a bogus failure. Also, we do check all endpoints created, so there is no need for the root to be checked.

Do not check server URL

---

.travis.yml

We no longer have a `default` travis job.

Publish to PyPI when building the docs

---

.travis.yml

Makes more sense in case of tarball failures.

Publish package on tarball test

---

.gitignore
pyproject.toml
setup.cfg

This ensure the wheel has the build dependencies and conforms to PEP 517.

add pyproject.toml

---

pyproject.toml

We need `setuptools_scm` at build time.

add setuptools_scm to pyproject.toml

---

requirements.txt

`pytz` is a main dependency that was not specified.

Fix mandatory dependencies

---

erddapy/erddapy.py
erddapy/utilities.py
requirements-dev.txt

@gmaze this is still a work in progress but it may help you in `argopy`. All methods that uses the netCDF response will use in memory whenever it is possible.
I'm still investigating how to integrate this with `fsspec` and possible lazy loads of netCDF files.

Nc response

---

erddapy/utilities.py
tests/test_url_builder.py
tests/test_utilities.py

`check_url_response` should be part of the public API and `urlopen` raises for status before returning bad data.

Raise for status and 'promote' check URL

---

.travis.yml

I'll check if the key needs to be refreshed later by testing it against the `gh-pages` directly.

fix docs publication

---

.gitignore

`_version.py` is managed by `setuptools_scm` and we don't want to commit notebooks with outputs anymore.

add more files to ignore

---

.pre-commit-config.yaml

Not sure if this was the cause of the broken docs but the new key and some tweaks on `master` fixed it. So I'm putting this file on the ignore list now.

ignore key file

---

CHANGES.txt
erddapy/erddapy.py
erddapy/utilities.py
tests/test_erddapy.py
tests/test_utilities.py

Adds several tests to make sure that keyword arguments can be passed appropriately
to requests.get, including simulating passing a timeout and querying through
a slow proxy.
Does not work on the removed request params, as that may be mixed in with auth.
Closes #131

Re-adds the ability to pass requests_kwargs to underlying request

---

erddapy/erddapy.py
tests/cassettes/test_erddap2_10.yaml
tests/test_erddapy.py

Removing the placeholder should be fine for older ERDDAP servers too.

ERDDAP 2.10 support

---

.github/workflows/publish.yml

We don't ship the tests with the source distribution.

Do not run tests on artifact publication

---

erddapy/erddapy.py

Hi,
As an ERDDAP beginner, I was having some trouble discovering what are valid attributes to categorize by. After realising that I could find them at the `erddap/categorize/index.html` page, I decided to improve the `get_categorize_url()` docstring for other users that may run into the same problem.
Summary of changes:
- In `get_categorize_url()` function: Add a line to the docstring explaining that valid attributes can be found in the categorize page.
Best,
Vini

Improve docstring for `get_categorize_url()` function

---

erddapy/erddapy.py

Recreate default griddap behaviour when subsetting gridded data

default stride to 1 in griddap

---

.github/workflows/publish.yml
.github/workflows/tests.yml

@callumrollo also using this one to test the CI failure you are experimenting in #192.

remove unused deps

---

setup.py

GitHub dependency graph only works if the name metadata is here.

fix github dependency graph issue

---

.pre-commit-config.yaml
erddapy/url_handling.py
tests/test_url_handling.py

This was a bad idea from the start. Users should not have an option of using an extension instead of a response code as args. We are already not using it for a while, so removing this should be harmless.

remove unused code

---

erddapy/erddapy.py

Hi,
this is just fixing a typo.
Summary of changes:
- Use same spelling for word 'initialize' throughout script
Best,
Vini

Standardise spelling

---

erddapy/erddapy.py

Hi,
When running `ERDDAP.griddap_initialize`, I would get the following warning: `FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.` My Pandas version is 1.4.0.
If merged, this PR will modify the `_griddap_get_constraints` function in order to remove the Pandas FutureWarning that was introduced in the latest Pandas versions.
I ran Pytest, Pre-Commit, and tested the function locally (by running `ERDDAP.griddap_initialize`), and things seem to be working properly.
Summary of changes:
* Replace `frame.append()` with `pd.concat()`
* Replace `table.index =` with `.set_index(drop=True)`
* Format code with Black
Thank you for any assistance you can provide,
Vini

Remove Pandas FutureWarning

---

setup.cfg

At some point we should probably vendor `parse_time_string` b/c that is not part of pandas' public API.

drop py36 and pandas <1

---

erddapy/erddapy.py
tests/test_to_objects.py

Hi,
this closes #250.
**Summary of changes**
- On method `ERDDAP.to_xarray`, check if response type is opendap. If it is, pass the URL to the `xarray.open_dataset` method instead of an nc dataset. This allows lazy loading of the dataset.
- Add corresponding tests (based on the `01a-griddap` notebook).
Please feel free to request any changes.
Thank you,
Vini

Use lazy loading when response type is OPeNDAP

---

tests/test_to_objects.py

Hi,
this is a follow-up to the discussion in #252. I got the test to work with the NERACOOS server. But there's a catch: the OPeNDAP request seems to fail after running the `griddap_initialize` method. My impression is that happens because that when that method is called, it adds the dataset bounds to the download URL, and the `xarray.open_dataset` method doesn't handle that well. I will look into that soon.
**Summary of changes**
- Refactor test to use NERACOOS WW3_EastCoast_latest dataset
- Modify fixture 'dataset_opendap'
Please feel free to request any changes.
Thank you,
Vini

Refactor test 'test_to_xarray_opendap'

---

erddapy/erddapy.py
tests/cassettes/test_erddap2_10.yaml
tests/test_to_objects.py

Hi,
this is in relation to #244. I wasn't sure of the best way to go about this, so I tried keeping it as simple as possible. Please let me know if there's an obvious way that I'm missing.
What I did was simply to set the number of `items_per_page` to a big number (initially it was `1e9`, but I thought that was excessive?) if the response is either `'csv'` or `'json'`. This doesn't require actually making the request, it just builds the URL. I couldn't find a "number of records" variable in the search response. I suppose I could set the `items_per_page` variable to that, but that would require making the request, and I understand that we just want the URL. Removing the `items_per_page` or `page` variables from the URL didn't make any difference.
To test, I added a fixture for the gliders …

Increase number per items on CSV, JSON searches

---

erddapy/core/url.py
erddapy/erddapy.py
erddapy/multiple_server_search.py
tests/test_erddapy.py
tests/test_netcdf_handling.py
tests/test_url_builder.py

Hi,
this is a downstream branch of #263, so it will be easier to review after merging that and #259. It includes two additional commits that move `get_search_url`, `get_info_url` and `get_categorize_url` from the `erddapy.erddapy` module to the `erddapy.core.url` module.
For `get_download_url`, it's a bit more tricky: it would incur in a circular import between `erddapy.core.url` and the newly-added `erddapy.core.griddap` module, because of the `urlopen` and `_urlopen` functions. So, I'm thinking whether I should move those functions to a new module (maybe `erddapy.core.helpers` or `erddapy.core.__init__`?). Please let me know what you think is best.
Thank you,
Vini
**Summary of changes** (in relation to #263):
- Move the `get_search_url`, `get_info_url`, and `get_categorize_url` to the …

Refactor url methods

---

environment.yml
erddapy/erddapy.py
requirements-dev.txt

Hi,
this is a fix to the problem mentioned in #267.
On the `ERDDAP.to_iris()` method, when the `cubes.realise_data()` method doesn't work, it realises the data by calling `cube.data`. The new versions of Iris prevent creating a `CubeList` object using `cube.data` objects (as they are Numpy Arrays and not cubes), so that behaviour was modified.
Summary of changes:
- Realise data by creating placeholder variable `_`
- Don't use `iris.cube.CubeList` for placeholder variable
Thanks,
Vini

Improve exception handling in method to_iris

---

erddapy/core/interfaces.py
erddapy/erddapy.py
requirements-dev.txt
tests/test_erddapy.py

Hi,
this PR creates module `core.interfaces`, with methods to use URLs to generate third-party datasets. These methods are used in the `ERDDAP` class.
I rebased the `classes` branch from #267 with this branch.
If you could pay special attention to review how `kwargs` are being propagated across methods, that would be great.
Thanks,
Vini

Interfaces

---

erddapy/__init__.py
erddapy/core/__init__.py

Hi,
while working on the docs for the core interface, I realised that the URL parsing and interfaces methods would have to be directly imported from their respective modules, rather than being accessed from the `erddapy` module. This seemed a bit unintuitive, so I added public methods directly to the `erddapy.__init__` module.
Users can then run:
```python
from erddapy import get_download_url, to_pandas
url = get_download_url(...)
df = to_pandas(url)
import erddapy
url = erddapy.get_download_url(...)
df = erddapy.to_pandas(url)
```
instead of
```python
from erddapy.core.url import get_download_url
from erddapy.core.interfaces import to_pandas
```
which seems much harder to do.
**Summary of changes:**
- Add public methods to `erddapy.__init__`
This allows using the URL parsing and …

Add public methods to erddapy module

---

erddapy/__init__.py
erddapy/core/__init__.py
notebooks/04-refactor-update.ipynb

Hi,
This PR adds `notebooks/04-refactor-update.ipynb` documenting how to use public methods from the core layer.
I intend to improve this in the future, but I just added a basic example for now.
This PR contains 3ed7d61057fa7231ac8c96b39de6f9bcae3dd667 from #281.
Thanks

Add notebook documenting usage of core layer

---

tests/test_erddapy.py
tests/test_url_handling.py

Remove the timeout test that was using a service killed by Heroku. We are really testing that httpx appropriately times out when a timeout is passed to it, and hopefully that is being tested upstream.
Closes  #289

Remove the timeout test

---

.github/workflows/tests.yml
setup.cfg

Starts testing against Python 3.11 and adds a classifier for it.

Add Python 3.11 support

---

.github/workflows/deploy-docs.yml
.github/workflows/pypi.yml
.pre-commit-config.yaml
notebooks/00-quick_intro.ipynb
notebooks/01a-griddap.ipynb
notebooks/02-extras.ipynb
notebooks/03-advanced_search.ipynb

Change the servers we hit when building the docs to stable ones. Or at least ones that won't kick us out for just building docs :-/

Re-write docs to avoid bad servers

---

erddapy/core/interfaces.py
erddapy/core/netcdf.py
erddapy/core/url.py
erddapy/erddapy.py
notebooks/00-quick_intro.ipynb
notebooks/01a-griddap.ipynb
tests/test_netcdf_handling.py
tests/test_to_objects.py

Hi,
This is something I caught while running the `ds = e.to_xarray(decode_times=False)` line in `02-extras.ipynb`.
**Summary of changes**
- Fix kwargs propagation for urlopen and third-party libraries
- Improve docstrings
- Add typing.Dict for type annotation

Fix kwargs propagation in interfaces module

---

erddapy/core/url.py
pyproject.toml
requirements-dev.txt
requirements.txt

Closes #299 
In this PR:
- We are still relying on a private function but that code is the best there is :-/
- We are pinning to pandas >=2.0. Should be OK b/c we are patching the previous released erddapies to work with older pandas only (conda-forge), there is nothing we can do for PyPI;
- Re-added the tag regex that was accidentally removed;
- Added the `dayfirst` and `yearfirst` options to `parse_dates`. Only the default work when calling it internally but a user has the option to convert the date themselves this way.

pandas 2.0 support

---

requirements.txt
tests/test_erddapy.py

Latest `httpx` change the OK report from `None` to 200 OK status. While the current version of the tests will work with past version of `httpx` I'm pinning to modern versions for maintainability.

fix httpx status check change

---

erddapy/servers/servers.py

Sometimes `erddapy` can "hang" when fetching the servers and we should add a time limit and fallback to the built-in file.

Add a timeout when fetching servers

---

.github/workflows/tests.yml
erddapy/core/griddap.py
erddapy/core/interfaces.py
erddapy/core/netcdf.py
erddapy/core/url.py
erddapy/erddapy.py
erddapy/multiple_server_search.py
pyproject.toml

Python 3.10 EOL is only in 2026-10 but this will allow us to move faster, drop some code, and avoid some deprecation warnings.  I'm not in a hurry to merge this but #328 should only be merged after this one.

Support Python 3.10 and up

---

erddapy/core/interfaces.py
tests/test_erddapy.py

`datetime.utcnow()` is deprecated in lieu from `datetime.datetime.now(datetime.UTC)`.

Fix datetime deprecation in Python >=3.11

---

.pre-commit-config.yaml
MANIFEST.in
erddapy/core/griddap.py
erddapy/core/interfaces.py
erddapy/core/netcdf.py
erddapy/core/url.py
erddapy/erddapy.py
erddapy/multiple_server_search.py
notebooks/00-quick_intro.ipynb
notebooks/01a-griddap.ipynb
notebooks/01b-tabledap.ipynb
notebooks/02-extras.ipynb
notebooks/03-advanced_search.ipynb
notebooks/04-refactor-update.ipynb
pyproject.toml
ruff.toml
tests/test_erddapy.py
tests/test_servers.py
tests/test_to_objects.py
tests/test_url_builder.py

While this will cause some churn we only have 3 open PRs, 2 are "merged" and the other one is a draft of an idea. That menas we only have 1 real open PR and the best time to change linters is now!

Move more lints to ruff

---

.pre-commit-config.yaml
erddapy/core/url.py

I'm planning on a bugfix relase ASAP b/c the `urlopen` functionality is broken in ERDDAP 2.23 without this PR.

Always quote params in queries

---

erddapy/core/url.py
tests/test_to_objects.py

I'm starting to wonder if we do need to quote all URLs. The behavior doesn't seem to be consistent as Bob told me. Maybe we should revert all this and quote only the rare cases where `"` is present. Anyway, let's give this one last go.

oddily ncCF datasets cannot be quoted

---

.pre-commit-config.yaml
erddapy/core/griddap.py
erddapy/erddapy.py
notebooks/01a-griddap.ipynb

Right now we need this extra step for `griddap` but we can skip it run that automatically every time a `dataset_id` is set.

Automatically call griddap_initialize if a dataset_id exists

---

erddapy/core/url.py
tests/test_url_handling.py

The date format change, the double quotes are still required, and there is now an odd variable order to the URL in order to make it a valid request.

Fix CO-OPS URL

---

.github/workflows/tests.yml

Let's try to reduce the load on the servers. We don't need to run everything in all OSes.

run all on Linux and latest on the rest
