ioos/erddapy

requirements.txt
=> fix dependencies

README.rst
=> Fix item list

erddapy/erddapy.py, erddapy/utilities.py, tests/test_utilities.py
@rsignell-usgs can you test this? I this works you should be able to pass requests options to the main class and then all the URL requests can inherit the payload and or authorization.
=> add auth machinery

erddapy/erddapy.py
=> remove loop in `get_var_by_attr`

erddapy/erddapy.py, erddapy/utilities.py
HI! I would like to add SalishSeaCast to the list of servers and I also corrected the IREMER's URL (it's shown to be incorrect [here](https://github.com/ropensci/rerddap/pull/69)). Let me know if there is anything else I should do!
=> Fix IFREMER URL and add SalishSeaCast to servers.

CHANGES.txt
=> Updated changelog

CHANGES.txt, erddapy/url_builder.py
Also moving to an f-string approach to make code more readable.
=> Closes #43

erddapy/url_builder.py, erddapy/utilities.py, setup.py
This PR is only to make the code a little bit more readable.
=> use f-strings

.travis.yml, requirements-dev.txt
Should help with the long running tests we have here.
=> Improve testing

.travis.yml
Not sure if we have all the dependencies yet...
=> Test Python 3.7

CHANGES.txt, erddapy/erddapy.py
@rsignell-usgs I can re-factor this later but if this works for you I can issue a new release as soon as we merge this one.
=> Optional iris cube output

CHANGES.txt, erddapy/erddapy.py, erddapy/utilities.py
Also fix a bug in to_iris where the data was not `realised`.
=> Re factor tmpfiles

CHANGES.txt, erddapy/__init__.py, erddapy/erddapy.py, erddapy/url_builder.py, erddapy/utilities.py, setup.py, versioneer.py
The code is Python 3 only now.
=> remove __future__ imports

.travis.yml, README.md, docs/source/conf.py, setup.py
Ping @mwengren 
Hopefully I got all the references to `pyoceans`.
=> move erddapy from pyoceans to ioos

setup.cfg, setup.py, tests/test_utilities.py
We don't want universal` wheel for a Python 3 only package.
=> fix wheel building

CHANGES.txt, erddapy/erddapy.py
@mwengren you will need this to run https://github.com/ocefpaf/ERDDAP_APP
=> Allow for multiple CSV responses in to_pandas

README.md
We had this in the docs but not in the README.
=> add erddap docs link

README.md, notebooks/quick_intro.ipynb
Should be easier for copy-n-paste users to install `erddapy`.
=> add install instructions

README.md, requirements-dev.txt
Iris may be renamed soon on PyPI but until then let's keep this note here.
=> add a note about iris name

.travis.yml, requirements-dev.txt, setup.cfg
Should help create valide source dists.
=> Check manifest

CHANGES.txt
=> Opdate changelog

docs/source/erddapy.rst
=> Closes #86

README.md
@choldgraf to avoid multiple PRs I merge this one after you comment that it satisfies #87.
=> Closes #87

erddapy/erddapy.py, erddapy/utilities.py
=> pass requests_kwargs to _check_url_response [fixes #100]

.travis.yml, erddapy/utilities.py
=> Test on Python 3.8

.coveragerc, setup.cfg
This is a continuation of #104.
=> remove left over from setup.py to cfg move

.gitignore, .pre-commit-config.yaml, .travis.yml, Makefile, docs/source/conf.py, erddapy/erddapy.py, erddapy/utilities.py, requirements-dev.txt, setup.cfg, tests/test_url_builder.py, tests/test_utilities.py
Add pre-commit config for erddapy.
=> Pre commit

.github/workflows/pre-commit.yml
With this we don't need to request every user to install and configure pre-commit.
=> GH actions for pre-commit

.isort.cfg, .pre-commit-config.yaml, .travis.yml, erddapy/erddapy.py, erddapy/utilities.py, setup.cfg, tests/test_url_builder.py, tests/test_utilities.py
Closes #98 
Work in progress, needs:
@emiliom this implements `distinct` only for `download_url` but it seems that it makes sense to add this too all URLs. Not sure what is the most sane way to do that yet.
PS: do you have a nice example of this in action for the notebook/documentation?
=> add server-side function distinct

erddapy/erddapy.py
=> more type annotations

CHANGES.txt, erddapy/utilities.py
Fetch the ERDDAP servers list from a canonical source:
https://github.com/IrishMarineInstitute/awesome-erddap
=> Closes #92

erddapy/utilities.py
See https://github.com/IrishMarineInstitute/awesome-erddap/pull/14
=> Use master URL and prevent listing servers without a short name

.travis.yml, erddapy/erddapy.py, setup.cfg, tests/test_url_builder.py
This is a metadata rich format that creates a better high level object in both `iris` and `xarray`.
=> Use the ncCF reponse

erddapy/erddapy.py, tests/test_url_builder.py
I'll add the `fsspec` support to the `to_xarray` method in another PR.
=> Closes 114

.gitignore, .travis.yml, docs/source/index.rst
Not sure if this is the only thing preventing them from being published. Maybe something else is broken :-/
=> Fix notebook name in the docs

erddapy/utilities.py
Show the message in the webpage in the exception. ERDDAP has some important tips there that can help users.
=> better exception message

erddapy/utilities.py
Thanks @emiliom for catching this one.
=> fixes #128

.isort.cfg, erddapy/erddapy.py, tests/test_to_objects.py, tests/test_url_builder.py
@shaunwbell this should fix #134 
See https://nbviewer.jupyter.org/urls/gist.githubusercontent.com/ocefpaf/715e4702135ba6749bb68a902449829e/raw/aafee9a0a0467c92786eb2e670ee2bd2946cc8ff/bug_134.ipynb
=> closes #134

.pre-commit-config.yaml, .travis.yml, docs/source/conf.py, erddapy/erddapy.py, requirements-dev.txt, requirements.txt, tests/test_erddapy.py, tests/test_to_objects.py, tests/test_url_builder.py
Download size:
```
Miniconda3-latest-Linux-x86_64.sh :: 88.7M
micromamba-0.5.2-h2a4a447_0.tar.bz2 :: 4.5M
```
Environment creation (solve+download):
```
miniconda 131.56s user 9.14s system 44% cpu 5:15.24 total
micromamba 98.10s user 16.04s system 104% cpu 1:48.86 total
```
=> use micromamba in Travis-CI

.travis.yml
This should speed up the CIs a little bit.
=> Drop Python 3.6

.travis.yml, MANIFEST.in, erddapy/erddaps.json, erddapy/utilities.py, setup.cfg
Closes #140 
Not the most elegant solution but it works for now.
=> ship a server list for offline usage

CHANGES.txt
=> update changelog for v0.7.2

.travis.yml, docs/source/conf.py, requirements-dev.txt
I'll have to rebuild the previous tags with this setup if this works.
=> try versioned docs

erddapy/erddapy.py, erddapy/url_handling.py
This should speed up returns when the URL and parameters are used.
=> cache urlopen

.pre-commit-config.yaml, docs/source/conf.py, docs/source/erddapy.rst, erddapy/erddapy.py, erddapy/url_handling.py, setup.py, tests/test_erddapy.py, tests/test_url_builder.py
@MathewBiddle this removes the need for the workaround in https://github.com/oceanhackweek/ohw19-project-co_locators/blob/master/colocate/erddap_query.py#L18, it makes sense to upstream that change to others don't have to workaround it as well.
=> Rstrip slash

erddapy/erddapy.py, tests/test_url_builder.py
This converts to lowercase all search terms as expected by ERDDAP.
=> normalize search terms

.github/workflows/publish.yml, .travis.yml
travis.org is dying a slow death and I cannot move this to travis.com. So let's just go to GH Actions then.
=> no longer release using Travis-CI

.github/workflows/publish.yml
Should fix the Publish PyPI GHA.
=> setup python to avoid ubuntu defaults

.github/workflows/publish.yml
Should fix artifact publication to PyPI
=> Publication to PyPI

code-of-conduct.md
This is nice to have and we will probably need for #165
=> add Code of Conduct

requirements-dev.txt, tests/test_to_objects.py
=> support latest iris

erddapy/erddapy.py, tests/test_erddapy.py
A simple refactor for using list comprehension to build the constraint url string . This reduces repeated code and might help with understanding the codebase for anyone working on issue #164
=> Refactor constraint url building into function

.github/workflows/tests.yml, environment.yml, requirements-dev.txt, tests/test_erddapy.py, tests/test_to_objects.py, tests/test_url_handling.py
First step to move away from Travis-CI.
=> run tests on GHA

README.md
=> add list of projects that use erddapy and that are similar to it

erddapy/erddapy.py, tests/test_erddapy.py
Implementation is a bit messy. Requires the user to call two functions of ERDDAP class. To test:
```python
e = ERDDAP(
server="CSWC",
protocol="griddap",
response='csvp'
)
e.dataset_id = "usgsCeCrm3"
e.griddap_initialise()
print(e.get_download_url())
```
=> formulate griddap download url

.pre-commit-config.yaml, erddapy/erddapy.py, notebooks/00-quick_intro.ipynb, notebooks/01-longer_intro.ipynb, notebooks/02-extras.ipynb, notebooks/03-searchfor.ipynb, tests/test_erddapy.py, tests/test_url_handling.py
Adding type hints and Americanizing spelling
=> Callum patch 1

erddapy/erddapy.py
Final type fix to make mypy happy. Checks that variables, constraints and dim_names are all not None before constructing griddap subset query
=> fix dim_names type error with check for None

erddapy/erddapy.py
raises a ValueError if user has not set dataset_id
=> check for dataset_id in griddap_initialize

.pre-commit-config.yaml, README.md, requirements-dev.txt
Latest mypy does not install all stub by default and installing them in the conda env is not "visible" in for the pre-commit interpreter. Let's see if we can make it work with this setup.
=> try latest mypy

.pre-commit-config.yaml, erddapy/multiple_server_search.py
@callumrollo it turns out all we needed was to update the pre-commits (`pre-commit autoupdate`), at least they are passing for me locally now.
=> Fix pre commit

.github/workflows/publish.yml
This will test tarballs both in releases and in PRs.
=> test tarballs in PRs

.github/workflows/tests.yml
Also updated the main branch name.
=> Do not fail fast

erddapy/servers.py
We cannot access those without credentials. I'm not even sure those should be in the original list.
=> Filter non-public servers

.github/workflows/publish.yml
Let's try this if-statement instead.
=> fix tarball tests

tests/cassettes/test_download_url_constrained.yaml, tests/cassettes/test_download_url_unconstrained.yaml, tests/cassettes/test_info_url.yaml, tests/cassettes/test_search_url_change_protocol.yaml, tests/cassettes/test_search_url_valid_request.yaml, tests/test_url_builder.py
Hit all URLs in tests to ensure they are valid.
=> Test urls in tests

.github/workflows/tests.yml, .pre-commit-config.yaml, .travis.yml, docs/source/conf.py, erddapy/__init__.py, erddapy/doc_helpers.py, erddapy/erddapy.py, erddapy/multiple_server_search.py, erddapy/netcdf_handling.py, erddapy/servers.py, erddapy/url_handling.py, requirements-dev.txt, tests/test_erddapy.py, tests/test_multiple_server_search.py, tests/test_netcdf_handling.py, tests/test_servers.py, tests/test_to_objects.py, tests/test_url_builder.py, tests/test_url_handling.py
Add Autodoc typehints and pydocstyle to improve docs readability.
=> Autodoc typehints

setup.cfg
This will improve PyPI navigation.
=> add project_urls

.github/workflows/tests.yml, tests/test_multiple_server_search.py
Also bump the multiple servers tests to py310.
=> Test on py310

erddapy/erddapy.py
=> safer way to ensure the constraint is time

.github/workflows/publish.yml, setup.cfg
And correct the project_urls metadata.
=> Fix release automation

.github/workflows/deploy-docs.yml, .github/workflows/tests.yml
This should make our CIs a bit faster.
=> use micromamba

.pre-commit-config.yaml, environment.yml, tests/test_to_objects.py
Hopefully this will fix the segfaults in our tests.
=> Fix segfaults

.github/dependabot.yml
=> add dependabot daily updates for GHA

erddapy/core/netcdf.py, tests/test_netcdf_handling.py
=> Manually delete the file to avoid Windows aggressive file lock

.github/workflows/deploy-docs.yml, .github/workflows/pypi.yml, .github/workflows/tests.yml
Use `mamba-org/setup-micromamba` instead of the deprecated `mamba-org/provision-with-micromamba`.
=> use setup-micromamba

erddapy/erddapy.py, tests/test_to_objects.py
=> make it safe to call griddap_initialize on opendap

.pre-commit-config.yaml, pyproject.toml
=> Pre commits

pyproject.toml
@callumrollo and @abkfenris I should've done this change a long time ago but I forgot.
1. Are you OK being listed here as maintainers?
2. Do you want to have your email listed?
=> Switch from authors to maintainers

.pre-commit-config.yaml
=> Fix interrogate deprecation warning

erddapy/core/url.py, erddapy/erddapy.py
=> Allow for empty dataset_id info URL

.github/workflows/deploy-docs.yml, .github/workflows/pypi.yml, .github/workflows/tests.yml, .github/workflows/tests_core.yml
This should be safer than using releases b/c they are unique and immutable, releases aren't.
=> pin gha using hashes

.pre-commit-config.yaml, erddapy/core/netcdf.py, pyproject.toml
=> Fix context loader

.github/workflows/tests.yml
Should be OK, all the dependencies are already available.
=> add py313 tests

.github/workflows/pypi.yml, .github/workflows/tests_core.yml
=> Update GHA and fix version string

.github/workflows/deploy-docs.yml, .pre-commit-config.yaml, notebooks/01a-griddap.ipynb, notebooks/01b-tabledap.ipynb
=> Update pre commits

.pre-commit-config.yaml, erddapy/servers/erddaps.json
Closes #397 
Thanks @MathewBiddle for the reminder!
=> Sync servers JSON

.github/workflows/deploy-docs.yml, .github/workflows/pypi.yml, .github/workflows/tests.yml, docs/source/index.rst, notebooks/01b-tabledap.ipynb, notebooks/02-extras.ipynb, notebooks/03-advanced_search.ipynb, notebooks/04-refactor-update.ipynb
=> Use canonical ERDDAP docs
